### ISSUE TITLE
Reducir el ancho de la barra de búsqueda

### ISSUE THREAD

**Issue by paulinabustos** [LabPLC/Laboratorio-de-datos#11]
La barra de búsqueda se ve de un tamaño desproporcionado de ancho.

**Comment by poguez** [comment]
¿cómo @paulinabustos ?
Pon un screenshot please.

**Comment by paulinabustos** [comment]
@poguez Me refiero a esta, sólo hay que reducirle un poco el ancho. 

![barrabusqueda](https://cloud.githubusercontent.com/assets/6033705/6507011/0667805a-c304-11e4-970b-138a07b09d10.JPG)
