### ISSUE TITLE
¿Quitar fotos de organizaciones? 

### ISSUE THREAD

**Issue by paulinabustos** [LabPLC/Laboratorio-de-datos#13]
@poguez ¿qué tan difícil sería quitar la foto de las organizaciones y que sólo sale el título?

Se ve bastante mal sin las fotos y para poner las fotos de todos necesitaríamos acordar con las secretarías el uso del logo. 

Si toma mucho tiempo quitar las fotos, entonces, mejor quitamos la vista de Organizaciones.

**Comment by tlacoyodefrijol** [comment]
por qué habría que acordar con las secretarías @paulinabustos ?

**Comment by paulinabustos** [comment]
Es lo que me comentó @ayouidaniel

**Comment by tlacoyodefrijol** [comment]
![fe9260366175ac94d553a4dcca127ed5](https://cloud.githubusercontent.com/assets/5587545/6493551/7ed54732-c289-11e4-917d-20a38d2d82ff.gif)
