### ISSUE TITLE
cambiar height del header a 95px

### ISSUE THREAD

**Issue by tlacoyodefrijol** [LabPLC/Laboratorio-de-datos#2]

**Comment by tlacoyodefrijol** [comment]
Ahorita se ve así:
![screen shot 2015-03-03 at 11 15 39 am](https://cloud.githubusercontent.com/assets/5587545/6466577/aff7cb1c-c196-11e4-95c7-2168e7d5836d.png)

Debe verse así 

![screen shot 2015-03-03 at 11 16 40 am](https://cloud.githubusercontent.com/assets/5587545/6466597/ced7b4fc-c196-11e4-8f22-2d78d1046060.png)

**Comment by poguez** [comment]
Va :dart:
