### ISSUE TITLE
Quitar comentarios recientes de plugin de disqus

### ISSUE THREAD

**Issue by paulinabustos** [LabPLC/Laboratorio-de-datos#21]
Dentro de la sección de Comentarios de cada dataset están apareciendo los comentarios recientes de disqus parace que son spam. Vamos a quitarlos. 

![image](https://cloud.githubusercontent.com/assets/6033705/6518663/d7aecf5c-c35d-11e4-88c0-8ebbb51b51c6.png)

@poguez ¿a quién le van a llegar los comentarios que se hagan a la página? Sería bueno que le lleguen a @ayouidaniel  y a alguién de nosotros para que los moderemos.

**Comment by paulinabustos** [comment]
@poguez podemos configurar el plugin con la cuenta laboratorio@labcd.mx para que no aparezcan los comentarios y la moderación.

**Comment by poguez** [comment]
listo :+1:
