### ISSUE TITLE
Redactar README

### ISSUE THREAD

**Issue by paulinabustos** [LabPLC/Laboratorio-de-datos#32]
Actualizar Readme con instrucciones y explicación de qué es el repositorio. Guía aquí:https://github.com/CodeandoMexico/repo-guidelines

**Comment by poguez** [comment]
:+1:

**Comment by zoek1** [comment]
considero que seria una buena idea apostar por un flow con [datacats](https://github.com/datacats/datacats).
¿Cómo ves @poguez?

**Comment by poguez** [comment]
Estaría bien enseñar como instalar la extensión en datacats. :+1: 
Hay que poner también el readme default estilo extensión de ckan.
