### ISSUE TITLE
Agregar menú de "Temáticas" a vista de "Datos"

### ISSUE THREAD

**Issue by paulinabustos** [LabPLC/Laboratorio-de-datos#6]
En la sección de "Datos" deberá ir un menú con las temáticas del los datos. 

¿Cuál será la mejor manera de agregar las temáticas @poguez? ¿Con labels?

**Comment by poguez** [comment]
Sí, con labels :smile:

**Comment by poguez** [comment]
La opción sería cambiar el locale de Etiquetas a temáticas y borrar los demás filtros:
¿Qué opinas @ayouidaniel ?

![screen shot 2015-03-05 at 4 27 35 am](https://cloud.githubusercontent.com/assets/732015/6503160/fc3a3474-c2ef-11e4-8ce2-b0d4a67e5850.png)

**Comment by paulinabustos** [comment]
Yup, yo creo que esa es la manera.
