### ISSUE TITLE
Página de inicio 

### ISSUE THREAD

**Issue by paulinabustos** [LabPLC/Laboratorio-de-datos#7]
Con secciones de ¡Bienvenido!, Datasets (con lista de los temas) y sección con datasets. 

@ayouidaniel - ¿cuál es el criteio para los datasets que aparecen en la página de Inicio? ¿Más populares? ¿úlimos datasets? 

![inicio](https://cloud.githubusercontent.com/assets/6033705/6471607/5f3f2a3e-c1a1-11e4-889c-01b12aa5c777.JPG)

**Comment by tellodaniel** [comment]
Los mas descargados

**Comment by paulinabustos** [comment]
@ayouidaniel - ¿ya tienes los textos de la página de Bienvenida?

**Comment by poguez** [comment]
Pongamos información definitiva

![screen shot 2015-03-05 at 2 06 19 am](https://cloud.githubusercontent.com/assets/732015/6501317/53092c1a-c2dc-11e4-8510-2729f1004fcb.png)
